---
title: "CA"
author: "Philipp Bayer"
date: "2022-09-13"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

## Introduction

Here, we run through a standard CA. The code is mostly based on https://rentzb.github.io/post/ca/ using the FactoMineR package.

```{r setup}
library(tidyverse)
library(FactoMineR)
library(factoextra)
#install.packages(c('factoextra', 'FactoMineR'))
```

For CA we need to make a contingency table, the number of responses/possible values for each level for each variable (column).

Let's do that!

```{r}
df <- readxl::read_xlsx('./data/MCA_Macropods_Data.xlsx', sheet = 'Macropods_Complete ind')
head(df)

```

```{r}
contingency <- df %>% gather(key=styles, value=values)
contingency$styles <- as.factor(contingency$styles) 
contingency$values <- as.factor(contingency$values)
dt <- with(contingency,table(styles,values)) 
dt
```

```{r}
contingency %>% ggplot(aes(x=values, fill=styles)) + geom_bar()
```

# Running the CA

```{r}
domains.CA <- CA(dt, graph=F)

```

```{r}
fviz_ca_biplot(domains.CA,repel=T)

```

```{r}
fviz_ca_biplot(domains.CA,repel=T,map="rowprincipal")

```

```{r}
fviz_ca_biplot(domains.CA,repel=T,map="colprincipal")

```


```{r}
fviz_screeplot(domains.CA,addlabels=T) + 
  geom_hline(yintercept=14.3,linetype=2,color="red")
```

What contributes to axis 1?
By column:
```{r}
fviz_contrib(domains.CA, choice="col",axes=1)

```

By row:

```{r}
fviz_contrib(domains.CA, choice="row",axes=1)

```

What contributes to axis 2?

```{r}
fviz_contrib(domains.CA, choice="col",axes=2)

```


```{r}
fviz_contrib(domains.CA, choice="row",axes=2)

```

# Quality of fit

cos = 1, good representation.

```{r}
fviz_ca_row(domains.CA, col.row = "cos2",
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"), 
             repel = TRUE)
```

```{r}
fviz_ca_col(domains.CA, col.col = "cos2",
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"), 
             repel = TRUE)
```

